### ISSUE TITLE
Move tours to examples repo

### ISSUE THREAD

**Issue by gvdongen** [restatedev/tour-of-restate#15]
```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/tour-of-restate/issues/16
- [ ] https://github.com/restatedev/tour-of-restate/issues/17
- [ ] https://github.com/restatedev/tour-of-restate/issues/18
```
